# Generated by Django 3.0.6 on 2020-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investingsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_id',
            field=models.CharField(default='UNDEFINED', max_length=100, primary_key=True, serialize=False),
        ),
    ]
