# Generated by Django 3.0.6 on 2020-05-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investingsite', '0002_auto_20200517_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_earnings',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.CharField(default='UNDEFINED', max_length=20, primary_key=True, serialize=False),
        ),
    ]
