# Generated by Django 3.0.6 on 2020-05-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investingsite', '0003_auto_20200527_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_earnings',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
