# Generated by Django 3.0.6 on 2020-05-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investingsite', '0005_auto_20200528_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_shares_outstanding',
            field=models.BigIntegerField(default=0),
        ),
    ]
