# Generated by Django 3.0.6 on 2020-06-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investingsite', '0006_stock_stock_shares_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_preferred_equity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_total_assets',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_total_liabilities',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_shares_outstanding',
            field=models.BigIntegerField(default=1),
        ),
    ]
